---
clone: 
  depth: 1
kind: pipeline
name: kernel pipeline
 
steps:
  - name: building kernel
    image: panchajanya1999/archlinux:latest
    commands:
      - "export token=$TOKEN"
      - "curl https://raw.githubusercontent.com/vijaymalav564/myscripts/master/kernel.sh | bash"
    environment: 
      TOKEN: 
        from_secret: token
