---
clone: 
  depth: 1
kind: pipeline
name: kernel pipeline
 
steps:
  - name: building kernel
    image: ubuntu:jammy-20211029
    commands:
      - cp -af sources.list /etc/apt/
      - cp -af 99own /etc/apt/apt.conf.d/
      - apt update && apt upgrade -y
      - ln -fs /usr/share/zoneinfo/Asia/Kolkata /etc/localtime && date
      - apt install -f -y git bison flex libxml2 libssl-dev bc zip ccache p7zip default-jre python3 python3-pip wget curl
      - "export token=$TOKEN"
      - "curl https://raw.githubusercontent.com/vijaymalav564/myscripts/master/kernel.sh | bash"
    environment: 
      TOKEN: 
        from_secret: token
